---
- name: RedHat | Install common packages
  yum: pkg={{ item }} state=present
  with_items: common_packages
  when: ansible_os_family == 'RedHat'

- name: Debian | Install common packages
  apt: pkg={{ item }} state=present
  with_items: common_packages
  when: ansible_os_family == 'Debian'

