---

- name: RedHat | Install common packages
  yum: pkg={{ item }} state=present
  with_items: common.packages
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Debian | Install common packages
  apt: pkg={{ item }} state=present
  with_items: common.packages
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Add tmux config
  copy: src={{ common.tmux_config_file }} dest=/etc/tmux.conf
  sudo: yes
