---

- name: RedHat | Install common packages
  yum: pkg={{ item }} state=present
  with_items: common_packages
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Debian | Install common packages
  apt: pkg={{ item }} state=present
  with_items: common_packages
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Add tmux config
  copy: src={{ common_tmux_config }} dest=/etc/tmux.conf
  sudo: yes
